version: "3.8"

services:

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.3
    ports:
      - "8082:8080"
    command: start-dev
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin

  redis:
    image: redis:7.2.4-bookworm
    ports:
      - "6379:6379"

  intershop-core:
    build:
      context: .
      dockerfile: intershop-core/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - payment
      - redis
      - keycloak
    environment:
      - SPRING_REDIS_HOST=redis
      - PAYMENT_URL=http://payment:8081
      - KEYCLOAK_HOST=keycloak

  payment:
    build:
      context: .
      dockerfile: payment/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - keycloak
    environment:
      - KEYCLOAK_HOST=keycloak